[package]
name = "nazzy_mini_games_installator"
version = "0.1.2"
edition = "2024"

[dependencies]
dirs = "6.0.0"
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
zip = "4.1.0"
